steps:
  - task: UseDotNet@2
    displayName: Use .NET SDK 5.0.x
    inputs:
      packageType: sdk
      version: 5.0.x

  - task: DotNetCoreCLI@2
    displayName: Compile
    inputs:
      command: build
      projects: 'Git-Credential-Manager.sln'
      arguments: '--configuration=Windows$(configuration)'

  - task: DotNetCoreCLI@2
    displayName: Run unit tests
    inputs:
      command: test
      projects: 'Git-Credential-Manager.sln'
      arguments: '--configuration=Windows$(configuration)'
      publishTestResults: true
      testRunTitle: 'Unit tests (Windows)'
